// This file is auto-generated by the `update-kc-gen` command. Do not edit it manually.
// Hash: 27d64fc3a2b0f948dd2af6837faa14e9772f26a3d1cd27f7ac7683d20515c128

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

import { lazy, Suspense, type ReactNode } from "react";

export type ThemeName = "keycloakify-v10-with-emails";

export const themeNames: ThemeName[] = ["keycloakify-v10-with-emails"];

export type KcEnvName = "MY_APP_URL" | "ACCOUNT_SETTING_URL";

export const kcEnvNames: KcEnvName[] = ["MY_APP_URL", "ACCOUNT_SETTING_URL"];

export const kcEnvDefaults: Record<KcEnvName, string> = {
    MY_APP_URL: "",
    ACCOUNT_SETTING_URL: ""
};

/**
 * NOTE: Do not import this type except maybe in your entrypoint.
 * If you need to import the KcContext import it either from src/login/KcContext.ts or src/account/KcContext.ts.
 * Depending on the theme type you are working on.
 */
export type KcContext = import("./login/KcContext").KcContext;

declare global {
    interface Window {
        kcContext?: KcContext;
    }
}

export const KcLoginPage = lazy(() => import("./login/KcPage"));

export function KcPage(props: { kcContext: KcContext; fallback?: ReactNode }) {
    const { kcContext, fallback } = props;
    return (
        <Suspense fallback={fallback}>
            {(() => {
                switch (kcContext.themeType) {
                    case "login":
                        return <KcLoginPage kcContext={kcContext} />;
                }
            })()}
        </Suspense>
    );
}
