// This file is auto-generated by the `update-kc-gen` command. Do not edit it manually.
// Hash: 1cdbebc0a18c2085b11c1cbc4ca461d333a29b022faa9e63e9125f48c07c3166

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

import { lazy, Suspense, type ReactNode } from "react";

export type ThemeName = "keycloakify-v2";

export const themeNames: ThemeName[] = ["keycloakify-v2"];

export type KcEnvName = "MY_APP_URL";

export const kcEnvNames: KcEnvName[] = ["MY_APP_URL"];

export const kcEnvDefaults: Record<KcEnvName, string> = {
    MY_APP_URL: ""
};

/**
 * NOTE: Do not import this type except maybe in your entrypoint.
 * If you need to import the KcContext import it either from src/login/KcContext.ts or src/account/KcContext.ts.
 * Depending on the theme type you are working on.
 */
export type KcContext = import("./login/KcContext").KcContext;

declare global {
    interface Window {
        kcContext?: KcContext;
    }
}

export const KcLoginPage = lazy(() => import("./login/KcPage"));

export function KcPage(props: { kcContext: KcContext; fallback?: ReactNode }) {
    const { kcContext, fallback } = props;
    return (
        <Suspense fallback={fallback}>
            {(() => {
                switch (kcContext.themeType) {
                    case "login":
                        return <KcLoginPage kcContext={kcContext} />;
                }
            })()}
        </Suspense>
    );
}
